// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyRuntime/Public/ArticyGlobalVariables.h"
#include "Kitty_Ao_Resgate_draft_GlobalVariables.generated.h"
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(push)
#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
#endif

/** Booleans that control whenever the player has already interacted with any npc */
UCLASS(BlueprintType)
class BEATEMUP_PROJECT_API UKitty_Ao_Resgate_draft_HasSpokenBeforeVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="HasSpokenBefore")
	UArticyBool* hasSpoken_npc2 = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="HasSpokenBefore")
	UArticyBool* hasSpoken_npc1 = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="HasSpokenBefore")
	UArticyBool* hasSpoken_npc3 = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="HasSpokenBefore")
	UArticyBool* knows_ReiCutelo = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="HasSpokenBefore")
	UArticyBool* knows_Joao = nullptr;
	
	 UKitty_Ao_Resgate_draft_HasSpokenBeforeVariables() 
	{
		hasSpoken_npc2 = CreateDefaultSubobject<UArticyBool>("hasSpoken_npc2");
		hasSpoken_npc1 = CreateDefaultSubobject<UArticyBool>("hasSpoken_npc1");
		hasSpoken_npc3 = CreateDefaultSubobject<UArticyBool>("hasSpoken_npc3");
		knows_ReiCutelo = CreateDefaultSubobject<UArticyBool>("knows_ReiCutelo");
		knows_Joao = CreateDefaultSubobject<UArticyBool>("knows_Joao");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		hasSpoken_npc2->Init<UArticyBool>(this, Store, TEXT("HasSpokenBefore.hasSpoken_npc2"), false);
		this->Variables.Add(hasSpoken_npc2);
		hasSpoken_npc1->Init<UArticyBool>(this, Store, TEXT("HasSpokenBefore.hasSpoken_npc1"), false);
		this->Variables.Add(hasSpoken_npc1);
		hasSpoken_npc3->Init<UArticyBool>(this, Store, TEXT("HasSpokenBefore.hasSpoken_npc3"), false);
		this->Variables.Add(hasSpoken_npc3);
		knows_ReiCutelo->Init<UArticyBool>(this, Store, TEXT("HasSpokenBefore.knows_ReiCutelo"), false);
		this->Variables.Add(knows_ReiCutelo);
		knows_Joao->Init<UArticyBool>(this, Store, TEXT("HasSpokenBefore.knows_Joao"), false);
		this->Variables.Add(knows_Joao);
	}
};

UCLASS(BlueprintType)
class BEATEMUP_PROJECT_API UKitty_Ao_Resgate_draft_AlreadySeenWantedPostVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="AlreadySeenWantedPost")
	UArticyBool* seenWantedPost_05 = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="AlreadySeenWantedPost")
	UArticyBool* seenWantedPost_04 = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="AlreadySeenWantedPost")
	UArticyBool* seenWantedPost_03 = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="AlreadySeenWantedPost")
	UArticyBool* seenWantedPost_02 = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="AlreadySeenWantedPost")
	UArticyBool* seenWantedPost_01 = nullptr;
	
	 UKitty_Ao_Resgate_draft_AlreadySeenWantedPostVariables() 
	{
		seenWantedPost_05 = CreateDefaultSubobject<UArticyBool>("seenWantedPost_05");
		seenWantedPost_04 = CreateDefaultSubobject<UArticyBool>("seenWantedPost_04");
		seenWantedPost_03 = CreateDefaultSubobject<UArticyBool>("seenWantedPost_03");
		seenWantedPost_02 = CreateDefaultSubobject<UArticyBool>("seenWantedPost_02");
		seenWantedPost_01 = CreateDefaultSubobject<UArticyBool>("seenWantedPost_01");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		seenWantedPost_05->Init<UArticyBool>(this, Store, TEXT("AlreadySeenWantedPost.seenWantedPost_05"), false);
		this->Variables.Add(seenWantedPost_05);
		seenWantedPost_04->Init<UArticyBool>(this, Store, TEXT("AlreadySeenWantedPost.seenWantedPost_04"), false);
		this->Variables.Add(seenWantedPost_04);
		seenWantedPost_03->Init<UArticyBool>(this, Store, TEXT("AlreadySeenWantedPost.seenWantedPost_03"), false);
		this->Variables.Add(seenWantedPost_03);
		seenWantedPost_02->Init<UArticyBool>(this, Store, TEXT("AlreadySeenWantedPost.seenWantedPost_02"), false);
		this->Variables.Add(seenWantedPost_02);
		seenWantedPost_01->Init<UArticyBool>(this, Store, TEXT("AlreadySeenWantedPost.seenWantedPost_01"), false);
		this->Variables.Add(seenWantedPost_01);
	}
};

UCLASS(BlueprintType)
class BEATEMUP_PROJECT_API UKitty_Ao_Resgate_draft_TestVarVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="TestVar")
	UArticyBool* DeuSalve = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="TestVar")
	UArticyBool* Interagiu = nullptr;
	
	 UKitty_Ao_Resgate_draft_TestVarVariables() 
	{
		DeuSalve = CreateDefaultSubobject<UArticyBool>("DeuSalve");
		Interagiu = CreateDefaultSubobject<UArticyBool>("Interagiu");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		DeuSalve->Init<UArticyBool>(this, Store, TEXT("TestVar.DeuSalve"), false);
		this->Variables.Add(DeuSalve);
		Interagiu->Init<UArticyBool>(this, Store, TEXT("TestVar.Interagiu"), false);
		this->Variables.Add(Interagiu);
	}
};

/** Global Articy Variables */
UCLASS(BlueprintType)
class BEATEMUP_PROJECT_API UKitty_Ao_Resgate_draft_GlobalVariables : public UArticyGlobalVariables
{
	GENERATED_BODY()
	
public:
	/** Booleans that control whenever the player has already interacted with any npc */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="HasSpokenBefore")
	UKitty_Ao_Resgate_draft_HasSpokenBeforeVariables* HasSpokenBefore = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="AlreadySeenWantedPost")
	UKitty_Ao_Resgate_draft_AlreadySeenWantedPostVariables* AlreadySeenWantedPost = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="TestVar")
	UKitty_Ao_Resgate_draft_TestVarVariables* TestVar = nullptr;
	
	 UKitty_Ao_Resgate_draft_GlobalVariables() 
	{
		/** create the namespaces */
		HasSpokenBefore = CreateDefaultSubobject<UKitty_Ao_Resgate_draft_HasSpokenBeforeVariables>("HasSpokenBefore");
		AlreadySeenWantedPost = CreateDefaultSubobject<UKitty_Ao_Resgate_draft_AlreadySeenWantedPostVariables>("AlreadySeenWantedPost");
		TestVar = CreateDefaultSubobject<UKitty_Ao_Resgate_draft_TestVarVariables>("TestVar");
		
		Init();
	}
	
	void Init() 
	{
		/** initialize the namespaces */
		HasSpokenBefore->Init(this);
		this->VariableSets.Add(HasSpokenBefore);
		AlreadySeenWantedPost->Init(this);
		this->VariableSets.Add(AlreadySeenWantedPost);
		TestVar->Init(this);
		this->VariableSets.Add(TestVar);
	}
	
	/** Get the default GlobalVariables (a copy of the asset). */
	UFUNCTION(BlueprintPure, Category="ArticyGlobalVariables", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyGV", keywords="global variables"))
	static UKitty_Ao_Resgate_draft_GlobalVariables* GetDefault(const UObject* WorldContext) 
	{
		return static_cast<UKitty_Ao_Resgate_draft_GlobalVariables*>(UArticyGlobalVariables::GetDefault(WorldContext));
	}
};
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(pop)
#endif
