// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "Kitty_Ao_Resgate_draft_Interfaces.generated.h"


/** UNINTERFACE generated from Articy Propriedade de personagem básica Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="Kitty_Ao_Resgate_draft_ Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UKitty_Ao_Resgate_draft_ObjectWithDefaultBasicCharacterFeatureFeature : public UInterface { GENERATED_BODY() };
class IKitty_Ao_Resgate_draft_ObjectWithDefaultBasicCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UKitty_Ao_Resgate_draft_DefaultBasicCharacterFeatureFeature* GetFeatureDefaultBasicCharacterFeature() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy Propriedade de personagem extendida Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="Kitty_Ao_Resgate_draft_ Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UKitty_Ao_Resgate_draft_ObjectWithDefaultExtendedCharacterFeatureFeature : public UInterface { GENERATED_BODY() };
class IKitty_Ao_Resgate_draft_ObjectWithDefaultExtendedCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UKitty_Ao_Resgate_draft_DefaultExtendedCharacterFeatureFeature* GetFeatureDefaultExtendedCharacterFeature() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy Personagem Externo Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="Kitty_Ao_Resgate_draft_ Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UKitty_Ao_Resgate_draft_ObjectWithPersonalidade_NarradorFeature : public UInterface { GENERATED_BODY() };
class IKitty_Ao_Resgate_draft_ObjectWithPersonalidade_NarradorFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UKitty_Ao_Resgate_draft_Personalidade_NarradorFeature* GetFeaturePersonalidade_Narrador() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy Personagem Genérico (NPC) Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="Kitty_Ao_Resgate_draft_ Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UKitty_Ao_Resgate_draft_ObjectWithPersonagem_Generico__NPCFeature : public UInterface { GENERATED_BODY() };
class IKitty_Ao_Resgate_draft_ObjectWithPersonagem_Generico__NPCFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UKitty_Ao_Resgate_draft_Personagem_Generico__NPCFeature* GetFeaturePersonagem_Generico__NPC() const
	{
		return nullptr;
	}
};
