// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyRuntime/Public/ArticyExpressoScripts.h"
#include "Kitty_Ao_Resgate_draft_GlobalVariables.h"
#include "Kitty_Ao_Resgate_draft_ExpressoScripts.generated.h"

UINTERFACE(Blueprintable)
class UKitty_Ao_Resgate_draft_MethodsProvider : public UInterface { GENERATED_BODY() };
class IKitty_Ao_Resgate_draft_MethodsProvider
{
	GENERATED_BODY()
	
public:
};

UCLASS(BlueprintType, Blueprintable)
class BEATEMUP_PROJECT_API UKitty_Ao_Resgate_draft_ExpressoScripts : public UArticyExpressoScripts
{
	GENERATED_BODY()
	
private:
	
	
private:
	
	mutable TWeakObjectPtr<UKitty_Ao_Resgate_draft_HasSpokenBeforeVariables> HasSpokenBefore = nullptr;
	mutable TWeakObjectPtr<UKitty_Ao_Resgate_draft_AlreadySeenWantedPostVariables> AlreadySeenWantedPost = nullptr;
	mutable TWeakObjectPtr<UKitty_Ao_Resgate_draft_TestVarVariables> TestVar = nullptr;
	mutable TWeakObjectPtr<UKitty_Ao_Resgate_draft_GlobalVariables> ActiveGlobals = nullptr;
	
	void SetGV(UArticyGlobalVariables* GV) const override
	{
		auto gv = Cast<UKitty_Ao_Resgate_draft_GlobalVariables>(GV);
		/** Initialize all GV namespace references (or nullify if we're setting to nullptr) */
		HasSpokenBefore = gv ? gv->HasSpokenBefore : nullptr;
		AlreadySeenWantedPost = gv ? gv->AlreadySeenWantedPost : nullptr;
		TestVar = gv ? gv->TestVar : nullptr;
		/** Store GVs */
		ActiveGlobals = gv;
	}
	
	UArticyGlobalVariables* GetGV() override
	{
		/** Return active global variables as set by SetGV */
		if(ActiveGlobals.IsValid()) { return ActiveGlobals.Get(); }
		return nullptr;
	}
	
	UClass* GetUserMethodsProviderInterface() override
	{
		return UKitty_Ao_Resgate_draft_MethodsProvider::StaticClass();
	}
	
public:
	
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(push)
	#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
	#endif
	 UKitty_Ao_Resgate_draft_ExpressoScripts() 
	{
		Conditions.Add(-770412083, [&]
		{
			return ConditionOrTrue(
				!(*HasSpokenBefore->hasSpoken_npc1)
			);
		});
		Instructions.Add(2108535397, [&]
		{
			(*HasSpokenBefore->hasSpoken_npc1) = true;
		});
		Conditions.Add(839802978, [&]
		{
			return ConditionOrTrue(
				(*HasSpokenBefore->hasSpoken_npc1)
			);
		});
		Instructions.Add(-747993832, [&]
		{
			(*HasSpokenBefore->knows_Joao) = true;
		});
		Conditions.Add(985518873, [&]
		{
			return ConditionOrTrue(
				(*HasSpokenBefore->hasSpoken_npc2) == false
			);
		});
		Instructions.Add(1369989158, [&]
		{
			(*HasSpokenBefore->hasSpoken_npc2) = true;
		});
		Conditions.Add(1507951235, [&]
		{
			return ConditionOrTrue(
				(*HasSpokenBefore->hasSpoken_npc2) == true
			);
		});
		Instructions.Add(-242692666, [&]
		{
			(*HasSpokenBefore->knows_ReiCutelo) = true;
		});
		Conditions.Add(-341283627, [&]
		{
			return ConditionOrTrue(
				!(*AlreadySeenWantedPost->seenWantedPost_01)
			);
		});
		Instructions.Add(-2097984489, [&]
		{
			(*AlreadySeenWantedPost->seenWantedPost_01) = true;
		});
		Conditions.Add(-648528103, [&]
		{
			return ConditionOrTrue(
				(*AlreadySeenWantedPost->seenWantedPost_01)
			);
		});
		Conditions.Add(402894584, [&]
		{
			return ConditionOrTrue(
				(*TestVar->Interagiu) == false
			);
		});
		Instructions.Add(1750125186, [&]
		{
			(*TestVar->Interagiu) = true;
		});
		Instructions.Add(775594419, [&]
		{
			(*TestVar->DeuSalve) = true;
		});
		Instructions.Add(-704034663, [&]
		{
			(*TestVar->DeuSalve) = false;
		});
		Conditions.Add(-1614847996, [&]
		{
			return ConditionOrTrue(
				(*TestVar->Interagiu) == true
			);
		});
		Conditions.Add(-1579479792, [&]
		{
			return ConditionOrTrue(
				(*TestVar->DeuSalve) == true
			);
		});
		Conditions.Add(1092028447, [&]
		{
			return ConditionOrTrue(
				(*TestVar->DeuSalve) == false
			);
		});
	}
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(pop)
	#endif
};
